

//AUT Action Types
export const LOGIN_USER = 'LOGIN_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'
export const SET_ERRORS = "SET_ERRORS"
export const SET_CURRENT_USER = 'SET_CURRENT_USER'


export const GET_USER_DETAILS = 'GET_USER_DETAILS'
export const GET_RECENT_TRANSACTION = 'GET_RECENT_TRANSACTION'

export const CREDIT_CARD_ADDED_SUCCESS = 'CREDIT_CARD_ADDED_SUCCESS'
export const CREDIT_CARD_ADDED_FAIL = 'CREDIT_CARD_ADDED_FAIL'
export const CREDIT_CARD_LIST = 'CREDIT_CARD_LIST'